### ISSUE TITLE
product

### ISSUE THREAD

**Issue by Akashshere19** [magefan/theme-frontend-optimized#6]
When i am click on prduct link or product name that time showing error
TypeError: strlen(): Argument #1 ($string) must be of type string, null given in /var/www/html/magento2/vendor/magefan/module-theme-optimized/Observer/LayoutLoadBeforeObserver.php:46

**Comment by magefan** [comment]
@Akashshere19 , could you please update the file  /var/www/html/magento2/vendor/magefan/module-theme-optimized/Observer/LayoutLoadBeforeObserver.php with this one

https://raw.githubusercontent.com/magefan/module-theme-optimized/main/Observer/LayoutLoadBeforeObserver.php

Let us know if it helps.
